### ISSUE TITLE
Getting consistent error while loading dataset

### ISSUE THREAD

**Issue by raagbtitl** [LauraPS1/TFEA.ChIP#1]
Hello,

I am facing issue regarding loading dataset : 

I used following R code for loading dataset:

data2=cbind(data1$Genes,as.numeric(data1$log2FoldChange),as.numeric(data1$pvalue))
colnames(data2)=c("Genes","log2FoldChange","pvalue")
dataset_creb <- preprocessInputData(as.data.frame(data2))

Error in `$<-.data.frame`(`*tmp*`, "Genes", value = c("917", "3699", "6261",  : 
  replacement has 7734 rows, data has 12
In addition: Warning message:
Some genes returned 1:many mapping to ENTREZ ID. Genes were assigned the first ENTREZ ID match found.

please let me know if there is any solution.

thanks,
rahul

**Comment by LauraPS1** [comment]
Hello, Rahul,

Without a sample of your dataset I can't replicate the exact same error you're having, but this usually happens when there are whitespaces in the gene names (i.e., " TP53 " instead of "TP53"). 

If this is the case with your dataset, you can use the function _trimws()_ to remove whitespaces from the gene IDs when generating the matrix _data2_ in your code.

Cheers

**Comment by raagbtitl** [comment]
Hello Laura,

I tried as you suggested but it does not work. I am attaching here the file. Please have a look. Thanks.

Rahul

[mydata.zip](https://github.com/LauraPS1/TFEA.ChIP/files/3296912/mydata.zip)

**Comment by LauraPS1** [comment]
I see that gene IDs are written using both upper and lowercase letters, ¿are you sure these aren't mouse genes? 
If that were the case, set the variable _mode_ in _preprocessInputData()_ to any of the mouse modes, for instance: 
`dataset_creb <- preprocessInputData( as.data.frame( data2 ), mode = "m2h" )`

I've updated the package, and if those are human IDs your code should run error-free.

Cheers

**Comment by raagbtitl** [comment]
Thanks for the help. these are the mouse gene symbols. I tried with mode="m2m" option, it showing the following error:
Error in .Call(R_curl_fetch_memory, enc2utf8(url), handle, nonblocking) : 
  reached elapsed time limit
Error in GeneID2entrez(gene.IDs = inputData$Genes, mode, return.Matrix = TRUE) : 
  We are having trouble reaching biomaRt.
Please, try again later.

then, also I tried with mode="m2h", then only able to read only 24 rows out of 10133.

Thanks

**Comment by LauraPS1** [comment]
The first error occurs when biomaRt servers are too busy, the second one has been solved in the last update. Bioconductor can take a while to add new versions, but you can download it from this repository or [following this link](https://github.com/LauraPS1/TFEA.ChIP_downloads/blob/master/TFEA.ChIP_1.5.3.tar.gz)

Cheers
